In [14]:
import pandas as pd
from utils import *

In [25]:
excel_input = 'output/output.xlsx'

excel_file = pd.ExcelFile(excel_input)

In [3]:
df = pd.read_excel(excel_input, sheet_name='Abrasives_raw_info')

In [6]:
unnamed_cols = [col for col in df.columns if 'Unnamed' in col]
split_indices = [df.columns.get_loc(col) for col in unnamed_cols]

# Ensure the indices are sorted and unique
split_indices = sorted(set(split_indices))

# Function to split the DataFrame at the specified column indices
def split_dataframe(df, split_indices):
    dfs = []
    start_col = 0
    for index in split_indices:
        dfs.append(df.iloc[:, start_col:index])
        start_col = index + 1
    # Append the last segment
    dfs.append(df.iloc[:, start_col:])
    return dfs

# Split the DataFrame
dfs = split_dataframe(df, split_indices)

In [15]:
for df in dfs:
  # si il existe une case ou il est écrit 'World total (rounded)' ou 'World total', ou n'imprt quele chose proche a ceci, crée une list new_df et append cette dataframe là dessus
  target_phrases = ['World total (rounded)', 'World total']

# Create a list to hold the dataframes that meet the condition
  new_df = []

  # Iterate through the split dataframes and check the condition
  for df in dfs:
      # Check if any cell in the dataframe matches the target phrases
      if df.apply(lambda row: any(match_element_in_text(target_phrases, str(cell)) for cell in row), axis=1).any():
          new_df.append(df)

In [19]:
new_df[0].head(4)

,text.1,text_1.1,text_2.1,text_3.1,text_4.1
0,NaN,Fused aluminum oxidee,Fused aluminum oxidee,Silicon carbidee,Silicon carbidee
1,NaN,2022,2023,2022,2023
2,United States,—,—,"40,000","40,000"
3,United States and Canada,"60,000","60,000",—,—

In [34]:
len(excel_file.sheet_names)  # 65 table!

82

:

In [29]:
sheet_names = excel_file.sheet_names

# Initialize remain_df as an empty list
remain_df = []

for name in sheet_names:
    df = pd.read_excel(excel_input, sheet_name=name)
    
    unnamed_cols = [col for col in df.columns if 'Unnamed' in col]
    split_indices = [df.columns.get_loc(col) for col in unnamed_cols]

    # Ensure the indices are sorted and unique
    split_indices = sorted(set(split_indices))

    # Split the DataFrame
    dfs = split_dataframe(df, split_indices)

    # List to hold the dataframes that meet the condition
    new_df = []

    # Target phrases
    target_phrases = ['World total (rounded)', 'World total']

    # Iterate through the split dataframes and check the condition
    for df in dfs:
        # Check if any cell in the dataframe matches the target phrases
        if df.apply(lambda row: any(match_element_in_text(target_phrases, str(cell)) for cell in row), axis=1).any():
            new_df.append(df)

    # Extend remain_df with new_df
    remain_df.extend(new_df)

In [32]:
remain_df

[                      text.1               text_1.1               text_2.1  \
 0                        NaN  Fused aluminum oxidee  Fused aluminum oxidee
 1                        NaN                   2022                   2023
 2              United States                      —                      —
 3   United States and Canada                 60,000                 60,000
 4                  Australia                 50,000                 50,000
 5                    Austria                 90,000                 90,000
 6                     Brazil                 50,000                 50,000
 7                      China                800,000                800,000
 8                     France                 40,000                 40,000
 9                    Germany                 80,000                 80,000
 10                     India                 40,000                 40,000
 11                     Japan                 15,000                 15,000
 12                    Mexico                      —                      —
 13                    Norway                      —                      —
 14                 Venezuela                      —                      —
 15           Other countries                 80,000                 80,000
 16     World total (rounded)              1,310,000              1,300,000
 17                       NaN                    NaN                    NaN
 18                       NaN                    NaN                    NaN

             text_3.1          text_4.1
 0   Silicon carbidee  Silicon carbidee
 1               2022              2023
 2             40,000            40,000
 3                  —                 —
 4                  —                 —
 5                  —                 —
 6             40,000            40,000
 7            450,000           450,000
 8             20,000            20,000
 9             35,000            35,000
 10             5,000             5,000
 11            60,000            60,000
 12            45,000            45,000
 13            80,000            80,000
 14            30,000            30,000
 15           200,000           200,000
 16         1,000,000         1,000,000
 17               NaN               NaN
 18               NaN               NaN  ,
                    text.1         text_1.1         text_2.1   text_3.1
 0                     NaN  Mine production  Mine production  Reserves4
 1                     NaN             2022            2023e        NaN
 2           United States              NaN              NaN        NaN
 3                   China            5,700            5,700     67,000
 4                 Germany               60               60        NaN
 5                    Iran              116              120      4,500
 6                  Mexico            1,000             1000     68,000
 7                Mongolia              425              930     34,000
 8                Pakistan               52               52        NaN
 9            South Africa              406              410     41,000
 10                  Spain              153              150     15,000
 11                Vietnam              218              170      3,400
 12        Other countries              190              170     50,000
 13  World total (rounded)            8,320            8,800    280,000
 14                    NaN              NaN              NaN        NaN
 15                    NaN              NaN              NaN        NaN
 16                    NaN              NaN              NaN        NaN
 17                    NaN              NaN              NaN        NaN
 18                    NaN              NaN              NaN        NaN
 19                    NaN              NaN              NaN        NaN
 20                    NaN              NaN              NaN        NaN
 21                    NaN              NaN              NaN        NaN
 22                    NaN              NaN              NaN        NaN
 23                    NaN              NaN              NaN        NaN
 24                    NaN              NaN              NaN        NaN
 25                    NaN              NaN              NaN        NaN
 26                    NaN              NaN              NaN        NaN
 27                    NaN              NaN              NaN        NaN
 28                    NaN              NaN              NaN        NaN
 29                    NaN              NaN              NaN        NaN
 30                    NaN              NaN              NaN        NaN
 31                    NaN              NaN              NaN        NaN
 32                    NaN              NaN              NaN        NaN,
                      text            text_1            text_2  \
 0                     NaN  Mine productione  Mine productione
 1                     NaN              2022              2023
 2           United States               NaN               NaN
 3                   China             1,000             1,000
 4              Kyrgyzstan                 6                 6
 5                 Morocco                 2                 2
 6                  Norway                20                20
 7          Peru (exports)                30                30
 8              Tajikistan               100               100
 9  World total (rounded)3             1,160             1,200

                          text_3
 0                     Reserves2
 1                           NaN
 2     Quantitative estimates of
 3  reserves were not available.
 4   China, Kyrgyzstan, and Peru
 5    have the largest reserves.
 6                           NaN
 7                           NaN
 8                           NaN
 9                           NaN  ,
                     text.1       text_1.1       text_2.1        text_3.1  \
 0                      NaN  Ferrosilicone  Ferrosilicone  Silicon metale
 1                      NaN           2022           2023            2022
 2           United States7              W              W               W
 3                Australia              —              —              48
 4                   Bhutan             75             80               —
 5                   Brazil            189            190             202
 6                   Canada             20             20              29
 7                    China          3,770          3,600           2,900
 8                   France             25             20              96
 9                  Germany              —              —              62
 10                 Iceland             79             80              49
 11                   India             59             60               —
 12              Kazakhstan             96            120               5
 13                Malaysia             91             80               —
 14                  Norway            195            200             144
 15                  Poland             47             50               —
 16                  Russia            572            570              54
 17                   Spain             46             50               6
 18                 Ukraine             28              2               —
 19         Other countries            144            100              79
 20  World total (rounded)8          5,440          5,200           3,670

           text_4.1
 0   Silicon metale
 1             2023
 2                W
 3               50
 4                —
 5              200
 6               30
 7            3,000
 8               90
 9               60
 10              50
 11               —
 12               5
 13               —
 14             140
 15               —
 16              50
 17               6
 18               —
 19              80
 20           3,800  ,
                    text.1            text_1.1            text_2.1  \
 0                     NaN  Smelter production  Smelter production
 1                     NaN                2022               2023e
 2           United States                 861                 750
 3               Australia               1,510               1,500
 4                 Bahrain               1,600               1,600
 5                  Brazil                 811               1,100
 6                  Canada               2,770               3,000
 7                   China              40,200              41,000
 8                 Iceland                e720                 730
 9                   India              e4,100               4,100
 10               Malaysia                e900                 980
 11                 Norway              e1,400               1,300
 12                 Russia               3,720               3,800
 13   United Arab Emirates               2,650               2,700
 14        Other countries               7,110               7,000
 15  World total (rounded)              68,400              70,000
 16                    NaN                 NaN                 NaN
 17                    NaN                 NaN                 NaN
 18                    NaN                 NaN                 NaN
 19                    NaN                 NaN                 NaN
 20                    NaN                 NaN                 NaN
 21                    NaN                 NaN                 NaN
 22                    NaN                 NaN                 NaN
 23                    NaN                 NaN                 NaN
 24                    NaN                 NaN                 NaN
 25                    NaN                 NaN                 NaN
 26                    NaN                 NaN                 NaN
 27                    NaN                 NaN                 NaN
 28                    NaN                 NaN                 NaN
 29                    NaN                 NaN                 NaN
 30                    NaN                 NaN                 NaN
 31                    NaN                 NaN                 NaN
 32                    NaN                 NaN                 NaN
 33                    NaN                 NaN                 NaN
 34                    NaN                 NaN                 NaN

             text_3.1          text_4.1
 0   Yearend capacity  Yearend capacity
 1               2022             2023e
 2              1,640             1,360
 3              1,730             1,730
 4              1,600             1,600
 5              1,280             1,280
 6              3,270             3,270
 7             44,300            45,000
 8                880               880
 9              4,060             4,060
 10             1,080             1,080
 11             1,460             1,460
 12             4,080             4,080
 13             2,790             2,790
 14            10,300            10,000
 15            78,500            79,000
 16               NaN               NaN
 17               NaN               NaN
 18               NaN               NaN
 19               NaN               NaN
 20               NaN               NaN
 21               NaN               NaN
 22               NaN               NaN
 23               NaN               NaN
 24               NaN               NaN
 25               NaN               NaN
 26               NaN               NaN
 27               NaN               NaN
 28               NaN               NaN
 29               NaN               NaN
 30               NaN               NaN
 31               NaN               NaN
 32               NaN               NaN
 33               NaN               NaN
 34               NaN               NaN  ,
                    text.1            text_1.1            text_2.1  \
 0                     NaN  Primary production  Primary production
 1                     NaN                2022               2023e
 2           United States                   —                   —
 3                   China             600,000             600,000
 4                  Japane               3,000               3,000
 5     Korea, Republic ofe               2,000               2,000
 6                 Russiae               5,000               5,000
 7        Other countries4                   —                   —
 8   World total (rounded)             610,000             610,000
 9                     NaN                 NaN                 NaN
 10                    NaN                 NaN                 NaN
 11                    NaN                 NaN                 NaN

                text_3.1
 0   Production capacity
 1                  2023
 2                     —
 3             1,000,000
 4                10,000
 5                16,000
 6                10,000
 7               e88,000
 8            e1,100,000
 9                   NaN
 10                  NaN
 11                  NaN  ,
                    text.1          text_1.1         text_2.1         text_3.1  \
 0                     NaN   Scrap and flake  Scrap and flake  Scrap and flake
 1                     NaN  Mine productione        Reserves8        Reserves8
 2                     NaN              2022             2023             2023
 3           United States            42,000           38,000            Large
 4                  Canada            15,000           15,000            Large
 5                   China            80,000           85,000        1,100,000
 6                 Finland           958,200           60,000            Large
 7                  France            15,000           10,000            Large
 8                   India            14,000           14,000            Large
 9      Korea, Republic of           910,200           12,000       11,000,000
 10             Madagascar            35,000           50,000            Large
 11                 Turkey            96,070            4,000          620,000
 12        Other countries            42,500           39,000            Large
 13  World total (rounded)           318,000          330,000            Large

             text_4.1          text_5.1      text_6
 0              Sheet             Sheet         NaN
 1   Mine productione  Mine productione   Reserves8
 2               2022              2023         NaN
 3                NaN               NaN  Very small
 4                NaN               NaN         NaN
 5                NaN               NaN      75,000
 6                NaN               NaN         NaN
 7                NaN               NaN         NaN
 8              1,000             1,000     110,000
 9                  —                 —         NaN
 10                 —                 —         NaN
 11                 —                 —         NaN
 12               200               200    Moderate
 13               NaN               NaN         NaN  ,
                    text.1         text_1.1         text_2.1   text_3.1
 0                     NaN  Mine production  Mine production  Reserves9
 1                     NaN             2022            2023e        NaN
 2           United States            1,010            1,000     23,000
 3               Argentina              913              910      6,500
 4               Australia            1,167            1,200   1094,000
 5                 Bolivia            1,214            1,200     22,000
 6                   Chile            1,274            1,400     26,000
 7                   China            3,480            3,400     72,000
 8                   India              694              690      8,000
 9              Kazakhstan            1,053              990        NaN
 10                 Mexico            6,195            6,400     37,000
 11                   Peru            3,079            3,100    110,000
 12                 Poland            1,316            1,300    *63,000
 13                 Russia            1,280            1,200     92,000
 14        Other countries            2,940            3,000     57,000
 15  World total (rounded)           25,600           26,000   *610,000
 16                    NaN              NaN              NaN        NaN
 17                    NaN              NaN              NaN        NaN
 18                    NaN              NaN              NaN        NaN
 19                    NaN              NaN              NaN        NaN
 20                    NaN              NaN              NaN        NaN
 21                    NaN              NaN              NaN        NaN
 22                    NaN              NaN              NaN        NaN
 23                    NaN              NaN              NaN        NaN
 24                    NaN              NaN              NaN        NaN
 25                    NaN              NaN              NaN        NaN
 26                    NaN              NaN              NaN        NaN
 27                    NaN              NaN              NaN        NaN
 28                    NaN              NaN              NaN        NaN,
                      text.1         text_1.1         text_2.1    text_3.1
 0                       NaN  Mine production  Mine production   Reserves7
 1                       NaN             2022            2023e         NaN
 2             United States                —                —     860,000
 3                 Australia            2,290            2,300    9140,000
 4                   Bolivia            3,000            3,000     310,000
 5                     Burma           e4,600            4,600     140,000
 6                    Canada               e2                2      78,000
 7                     China          e40,000           40,000     640,000
 8                 Guatemala               24               24         NaN
 9                      Iran             e500              500         NaN
 10               Kazakhstan             e300              300         NaN
 11               Kyrgyzstan               40               40     260,000
 12                     Laos             e220              220         NaN
 13                   Mexico             e700              700      18,000
 14                 Pakistan              e79               80      26,000
 15                   Russia            4,300            4,300     350,000
 16               Tajikistan           21,000           21,000      50,000
 17                   Turkey           e5,800            6,000      99,000
 18                  Vietnam              250              250         NaN
 19  World total (rounded)10           83,100           83,000  >2,000,000
 20                      NaN              NaN              NaN         NaN
 21                      NaN              NaN              NaN         NaN
 22                      NaN              NaN              NaN         NaN
 23                      NaN              NaN              NaN         NaN
 24                      NaN              NaN              NaN         NaN
 25                      NaN              NaN              NaN         NaN
 26                      NaN              NaN              NaN         NaN
 27                      NaN              NaN              NaN         NaN
 28                      NaN              NaN              NaN         NaN
 29                      NaN              NaN              NaN         NaN
 30                      NaN              NaN              NaN         NaN
 31                      NaN              NaN              NaN         NaN
 32                      NaN              NaN              NaN         NaN
 33                      NaN              NaN              NaN         NaN
 34                      NaN              NaN              NaN         NaN
 35                      NaN              NaN              NaN         NaN,
                   text.1         text_1.1         text_2.1           text_3.1

In [33]:
def save_dfs_to_excel(dfs, filename):
    with pd.ExcelWriter(filename) as writer:
        for i, df in enumerate(dfs):
            df.to_excel(writer, sheet_name=f'Sheet{i+1}', index=False)

# Save the DataFrames to an Excel file
save_dfs_to_excel(remain_df, 'needed_tables.xlsx')